In [1]:
import pandas as pd
import numpy as np
from tslearn.metrics import dtw
from tslearn import metrics
import time

/public/home/weixun/.conda/envs/rl/lib/python3.8/site-packages/tslearn/bases/bases.py:15: UserWarning: h5py not installed, hdf5 features will not be supported.
Install h5py to use hdf5 features: http://docs.h5py.org/
  warn(h5py_msg)


In [2]:
a = np.random.normal(3, 2.5, size=(2, 100))

In [3]:
dtw(a[0], a[1])

17.678760729740112

In [4]:
a

array([[10.85968644,  3.93538877,  6.08667609, -0.48747041, -0.31829934,
         5.11917219,  2.21688888,  3.23922264,  6.15848245,  2.92672127,
         3.40367783,  5.25405333,  4.38819601, -0.82431024,  2.18160542,
        -2.3034595 ,  3.61721955,  2.22149807,  1.59420232,  1.61697651,
        -2.95402115,  2.63715146, 10.89077467,  8.55052713,  4.5590141 ,
         1.7476846 ,  3.65774083,  6.0124155 ,  3.79660198,  1.36425677,
         3.88051921,  4.74249447,  0.75684314,  5.96313214,  2.67378472,
         3.70747233,  2.85808626, -0.91434159,  0.73523303,  5.55675403,
         2.86737638,  3.22850334,  6.41312172,  4.55242505, -0.89636086,
         7.98930045,  7.21515591,  0.61401715,  1.90875207,  1.52802277,
         1.50919231, -0.31855064,  3.52904737,  5.38457247,  3.58393022,
         4.48097333,  5.32709972,  6.73957912,  1.19219096,  1.59060663,
         4.76326227, -1.79630148,  2.72078334,  8.21157095,  8.96064334,
         1.1825839 ,  2.58395854,  1.92730851,  0.2

In [5]:
a = [1,2,3]
b = [1,2,2,3,4]
dtw(a, b)

1.0

In [6]:
matrix = []
for i in range(3):
    p1 = a[i]
    m = []
    for j in range(5):
        p2 = b[j]
        x = np.power((p1-p2), 2)
        m.append(x)
    print(m)
    matrix.append(m)
print('---')
matrix

[0, 1, 1, 4, 9]
[1, 0, 0, 1, 4]
[4, 1, 1, 0, 1]
---


[[0, 1, 1, 4, 9], [1, 0, 0, 1, 4], [4, 1, 1, 0, 1]]

In [7]:
metrics.dtw_path(a, b)

([(0, 0), (1, 1), (1, 2), (2, 3), (2, 4)], 1.0)

In [8]:
metrics.dtw_path_from_metric(matrix)

ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required by check_pairwise_arrays.

In [9]:
from sklearn.metrics import pairwise_distances
a = np.array(a).reshape(1, -1)
b = np.array([2,3,2]).reshape(1, -1)

pairwise_distances(a, b)

array([[1.73205081]])

In [10]:
sum = 0
for i in range(3):
    sum += np.power((a[0,i] - b[0,i]), 2)
sum

3

In [11]:
rng = np.random.RandomState(0)
s1, s2 = rng.rand(5, 2), rng.rand(6, 2)

In [12]:
s1, s2

(array([[0.5488135 , 0.71518937],
        [0.60276338, 0.54488318],
        [0.4236548 , 0.64589411],
        [0.43758721, 0.891773  ],
        [0.96366276, 0.38344152]]),
 array([[0.79172504, 0.52889492],
        [0.56804456, 0.92559664],
        [0.07103606, 0.0871293 ],
        [0.0202184 , 0.83261985],
        [0.77815675, 0.87001215],
        [0.97861834, 0.79915856]]))

In [13]:
m = pairwise_distances(s1, s2)
m

array([[0.30612356, 0.2112843 , 0.7891329 , 0.54148195, 0.27670999,
        0.43793039],
       [0.18963685, 0.38229325, 0.70162138, 0.64973151, 0.36942074,
        0.45378731],
       [0.38621822, 0.31477278, 0.66072543, 0.44455307, 0.41940497,
        0.57573824],
       [0.50704448, 0.13477076, 0.8842009 , 0.42153982, 0.34126404,
        0.54890083],
       [0.2252094 , 0.67115269, 0.94052292, 1.04491552, 0.52073358,
        0.41598597]])

In [14]:
m.shape, s1.shape, s2.shape

((5, 6), (5, 2), (6, 2))

In [15]:
metrics.dtw_path_from_metric(m, metric='precomputed')

([(0, 0), (0, 1), (1, 2), (2, 3), (3, 4), (4, 5)], 2.4208323179319198)

In [16]:
dp = np.zeros((5, 6))
dp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
for i in range(5):
    for j in range(6):
        if i==0 and j==0:
            dp[i, j] = m[i, j]
            continue
        a, b, c = 10, 10, 10
        if i >=1 and j>=1:
            a = dp[i-1, j-1]
        if i>=1:
            b = dp[i-1, j]
        if j>=1:
            c = dp[i, j-1]
        dp[i, j] = m[i,j] + min(min(a, b), c)
dp

array([[0.30612356, 0.51740786, 1.30654076, 1.84802271, 2.1247327 ,
        2.56266309],
       [0.49576041, 0.68841681, 1.21902923, 1.86876075, 2.21744344,
        2.57852001],
       [0.88197863, 0.81053319, 1.34914224, 1.6635823 , 2.08298727,
        2.65872551],
       [1.3890231 , 0.94530396, 1.69473409, 1.77068207, 2.00484634,
        2.55374717],
       [1.6142325 , 1.61645665, 1.88582688, 2.73964961, 2.29141564,
        2.42083232]])

In [59]:
plt_data = pd.read_csv('plt_data.csv')
all_val = pd.read_csv('all_val.csv')
f_13 = pd.read_csv('res/final_13.csv')
f_13 = f_13[f_13.columns[1:]]
predict = pd.read_csv('predict.csv')
plt_data.shape, all_val.shape, f_13.shape, predict.shape 

((886, 3), (11244, 18), (26329, 419), (11244, 1))

In [60]:
IN = plt_data[plt_data['kind'] == 'IN']
IN

no  len_trace kind
170   536_02_-1         76   IN
171  1181_02_-1         89   IN
172  1182_02_-1         89   IN
173    45_07_-1         78   IN
174   363_07_-1         94   IN
..          ...        ...  ...
311  1627_52_-1         58   IN
312   749_54_-1         50   IN
313  1141_54_-1         54   IN
314  1142_54_-1         54   IN
315  1186_54_-1         48   IN

[146 rows x 3 columns]

In [61]:
num = 0
fn_num = 0
fn_will_t = 0
tp_num = 0
for i in IN.index:
    FN = all_val[(all_val['no'] == IN.loc[i]['no']) &
                 (all_val['label'] != predict['label'])]
    TP = all_val[(all_val['no'] == IN.loc[i]['no']) &
                 (all_val['label'] == predict['label'])]
    # print(FN.shape[0], )
    fn_num += FN.shape[0]
    tp_num += TP.shape[0]
    if FN.shape[0] < TP.shape[0]:
        fn_will_t += (FN.shape[0] + TP.shape[0])
        num += 1
num, fn_will_t, fn_num, tp_num, fn_num+tp_num, len(IN.index), 

(116, 2800, 907, 2472, 3379, 146)

In [62]:
IN2 = plt_data[plt_data['kind'] == 'IN2']
num = 0
fp_num = 0
fp_will_t = 0
tn_will_f = 0
tn_num = 0
for i in IN2.index:
    FP = all_val[(all_val['no'] == IN2.loc[i]['no']) &
                 (all_val['label'] != predict['label'])]
    TN = all_val[(all_val['no'] == IN2.loc[i]['no']) &
                 (all_val['label'] == predict['label'])]
    # print(FN.shape[0], )
    fp_num += FP.shape[0]
    tn_num += TN.shape[0]
    if FP.shape[0] < TN.shape[0]:
        fp_will_t += FP.shape[0]
        num += 1
    else:
        tn_will_f += TN.shape[0]
num, fp_will_t, fp_num, tn_num, fp_num+tn_num, len(IN2.index), tn_will_f

(227, 537, 631, 2641, 3272, 253, 63)

In [63]:
FP = plt_data[plt_data['kind'] == 'FP']
num = 0
for i in FP.index:
    i = FP.loc[i]
    num += all_val[all_val['no'] == i['no']].shape[0]
num

20

In [64]:
TP = plt_data[plt_data['kind'] == 'TP']
TN = plt_data[plt_data['kind'] == 'TN']

In [188]:
all_val[all_val['no'].isin(IN2['no'])]

0              1             2             3              4  \
5624   1.697074e+04    9581.888625  1.442969e+04  9.222122e+03   16632.002024   
5626  -5.415024e+06   20309.179740 -3.689564e+06  1.730858e+06  460398.435854   
5628   2.056466e+04  -33422.609222 -1.346922e+04  2.414103e+03   -7743.543190   
5629   1.254620e+04   -3653.118393 -2.687791e+04 -2.933456e+04  -28614.335957   
5633  -2.987313e+05   66186.939351 -3.572391e+05  3.889809e+05  252910.940797   
...             ...            ...           ...           ...            ...   
11234 -2.271234e+04  127722.666633  3.702868e+04  1.938105e+04  147517.215014   
11235 -3.013810e+05  -37595.631219  1.066764e+05 -5.161285e+04  -57000.618718   
11237 -4.329178e+05  417955.792263  1.085056e+05 -3.581504e+03  111679.237665   
11240  1.170751e+04   70685.995245 -8.875503e+04 -1.272647e+05   10568.479070   
11241 -1.544781e+05  -23436.085179 -3.635930e+04 -3.582689e+04  -58600.985022   

                   5             6              7              8  \
5624   -13372.156089 -1.013209e+04    3430.582631   -2572.921555   
5626  -584834.057856  1.006428e+06  639904.470921  -48552.906808   
5628    -1177.949761  1.799619e+04   11301.819911    4639.086539   
5629    20140.871041  1.883240e+04   -1407.985197   56971.368551   
5633   411249.606950  1.120160e+05 -449321.306186   91889.919897   
...              ...           ...            ...            ...   
11234  -13950.896993 -5.380705e+04   36337.385006   36884.956171   
11235   54696.279749 -1.565438e+05  -78931.913076  108563.412861   
11237  -35840.893326 -1.425381e+05    4643.782285   24533.934191   
11240  -35869.567246 -3.362009e+04 -131626.131060  -13116.039656   
11241   14606.418958 -5.936410e+04    3858.395726   52611.576099   

                   9             10             11             12  \
5624       30.131705   -4750.626614  -33359.374402    8000.263443   
5626  -556225.344649  409257.881363  904704.048670 -135106.488980   
5628      667.274145   -4063.002154  -51102.995337    -182.998805   
5629   -34157.867697   -9743.915749  -51821.536019    8371.677856   
5633   272893.920216 -274350.021366  273197.398510  -28859.926195   
...              ...            ...            ...            ...   
11234  -20760.848766    1847.499934   -6315.979475  -21772.722426   
11235  -21456.778418   49237.143951   46922.805786   40789.875676   
11237   32956.224793   16129.679981   60534.252084   41552.658205   
11240  -34033.952964   77942.391820  -36894.387439  -28317.806685   
11241  -18864.434775   -4829.237064    3617.526366  -14330.429733   

                  13             14          no  label     id  
5624    -1035.441781    9822.350976   378_42_-1      0  17133  
5626   269526.977262 -216617.347064    35_02_-1      0   1844  
5628     7922.217017   -4721.467563   803_35_-1      0   5299  
5629      924.704314   -3662.258347  1032_18_-1      0  20240  
5633  -383280.477770  168019.378234    35_02_-1      0   1849  
...              ...            ...         ...    ...    ...  
11234   24842.307690  -21195.231837  1309_50_-1      0  11900  
11235  -47238.398143   34209.218229   113_30_-1      0  15507  
11237   70999.278196   55994.281670   871_32_-1      0   4208  
11240  -80691.725216  -42209.720577  1129_40_-1      0   2289  
11241   -2765.984773   -7617.149932    21_54_-1      0  25308  

[3272 rows x 18 columns]

In [66]:
FP.shape, TP.shape, TN.shape, IN2.shape

((8, 3), (157, 3), (309, 3), (253, 3))

In [71]:
FP

no  len_trace kind
316  1233_06_-1         22   FP
317   971_08_-1         41   FP
318   328_18_-1         29   FP
319   675_20_-1         35   FP
320  1300_37_-1         17   FP
321  1272_42_-1         90   FP
322   962_49_-1         19   FP
323  1510_52_-1         14   FP

In [189]:
FP_val = all_val[all_val['no'].isin(FP['no'])]
TP_val = all_val[all_val['no'].isin(TP['no'])]
TN_val = all_val[all_val['no'].isin(TN['no'])]
IN2_val = all_val[all_val['no'].isin(IN2['no'])]

In [76]:
FP_val[['no', 'label', 'id']].head()

no  label     id
5781  1272_42_-1      0  16741
6300  1272_42_-1      0  16746
6430   328_18_-1      0  20681
6479  1272_42_-1      0  16721
6549   962_49_-1      0  19799

In [91]:
TP_val[['no', 'label', 'id']].head()

no  label    id
0  1839_08_-1      1  9034
1  1839_08_-1      1  9035
2  1839_08_-1      1  9036
3  1839_08_-1      1  9037
4  1839_08_-1      1  9038

In [178]:
TN_val[['no', 'label', 'id']]

no  label     id
5622    426_11_-1      0  25811
5623    494_06_-1      0    446
5625   2205_08_-1      0  13111
5627    783_08_-1      0  13444
5630    752_31_-1      0   7553
...           ...    ...    ...
11236   627_49_-1      0  22986
11238    51_06_-1      0    561
11239    96_32_-1      0   7703
11242    55_30_-1      0  16164
11243  1171_49_-1      0  18987

[2330 rows x 3 columns]

In [133]:
for i in f_13.loc[9034].index[1:]:
    print(i, f_13.loc[9034][i])

girth 89.18376505374908
girth_full 92.18376505374908
area 406.5
elongation -1.622772686357734
eccentricity 0.924461298742412
convexity 1.1705989566556134
recty 0.6851597306737102
roundness 0.6011204875260896
major_axis 38.42509460449219
minor_axis 14.650562286376951
cent_m0 5811.216106325388
cent_m1 4551.648301899433
cent_m2 34788.577729940414
cent_m3 1182.5537109375
cent_m4 -8318.532419453375
cent_m5 -18409.539570387453
cent_m6 16081.33715057373
hu_m0 0.2456986263275028
hu_m1 0.0337871252767858
hu_m2 0.0004384213541954
hu_m3 3.216637925234359e-05
hu_m4 -3.0611979295809662e-09
hu_m5 -5.0641294832720295e-06
hu_m6 -2.284843521834047e-09
contrast 3.5742926215203275
dissimilarity 0.0478606986524761
homogeneity 0.9989648413797372
energy 0.9989432255068208
correlation 0.5635515845174316
ASM 0.9978875677859712
label 1
dense 317.5319095427219
girth_0 91.35533833503725
girth_full_0 93.35533833503725
area_0 422.5
elongation_0 -1.6108870997583329
eccentricity_0 0.9237435399580886
convexity_0 1.15

In [159]:
def get_matrix(no):
    m = []
    idx = list(dict(f_13.loc[no].items()).values())[1:]
    t = idx[0: 30]
    t.append(idx[31])
    m.append(t)
    for i in range(1, 13):
        m.append(idx[i*31+1: (i+1)*31+1])
    return m

In [186]:
# TP内部比较
m1 = get_matrix(9034)
m2 =  get_matrix(9035)
m = pairwise_distances(m1, m2)
print(m.shape)
a, b = metrics.dtw_path_from_metric(m, metric='precomputed')
b

(13, 13)


76128.0099705541

In [185]:
# TP FP比较
m1 = get_matrix(9034)
m2 =  get_matrix(16741)
m = pairwise_distances(m1, m2)
print(m.shape)
a, b = metrics.dtw_path_from_metric(m, metric='precomputed')
b

(13, 13)


915925.5651279001

In [184]:
# FP内部比较
m1 = get_matrix(16746)
m2 =  get_matrix(16741)
m = pairwise_distances(m1, m2)
print(m.shape)
a, b = metrics.dtw_path_from_metric(m, metric='precomputed')
b

(13, 13)


116533.45825757032

In [183]:
# TN内部比较
m1 = get_matrix(13444)
m2 =  get_matrix(7553)
m = pairwise_distances(m1, m2)
print(m.shape)
a, b = metrics.dtw_path_from_metric(m, metric='precomputed')
b

(13, 13)


349405.7422694879

In [182]:
# TN FP比较
m1 = get_matrix(13444)
m2 =  get_matrix(16741)
m = pairwise_distances(m1, m2)
print(m.shape)
a, b = metrics.dtw_path_from_metric(m, metric='precomputed')
b

(13, 13)


206115.46834619713

In [187]:
# TN TP比较
m1 = get_matrix(13444)
m2 =  get_matrix(9034)
m = pairwise_distances(m1, m2)
print(m.shape)
a, b = metrics.dtw_path_from_metric(m, metric='precomputed')
b

(13, 13)


921721.9633281257

In [191]:
IN2_val[['no', 'label', 'id']]

no  label     id
5624    378_42_-1      0  17133
5626     35_02_-1      0   1844
5628    803_35_-1      0   5299
5629   1032_18_-1      0  20240
5633     35_02_-1      0   1849
...           ...    ...    ...
11234  1309_50_-1      0  11900
11235   113_30_-1      0  15507
11237   871_32_-1      0   4208
11240  1129_40_-1      0   2289
11241    21_54_-1      0  25308

[3272 rows x 3 columns]

In [193]:
all_val[(all_val['no'] == '378_42_-1') & (all_val['label'] != predict['label'])]

0             1             2            3             4  \
8496  13195.173256  10395.805496  23102.149103  3318.138733  13877.171696   

                5             6             7             8            9  \
8496 -1690.037042 -16117.160379  10141.304226 -13558.424652 -3718.737602   

               10            11           12            13           14  \
8496 -3236.956071 -37970.919723  8811.941712 -12207.098021 -3425.680724   

             no  label     id  
8496  378_42_-1      0  17134

In [198]:
all_val[(all_val['no'] == '35_02_-1') & (all_val['label'] != predict['label'])]

0             1              2              3  \
5633 -298731.347609  66186.939351 -357239.075775  388980.903905   

                  4             5              6              7             8  \
5633  252910.940797  411249.60695  112016.014934 -449321.306186  91889.919897   

                  9             10            11            12            13  \
5633  272893.920216 -274350.021366  273197.39851 -28859.926195 -383280.47777   

                 14        no  label    id  
5633  168019.378234  35_02_-1      0  1849

In [199]:
all_val[(all_val['no'] == '35_02_-1') & (all_val['label'] == predict['label'])].head()

0              1             2             3             4  \
5626 -5.415024e+06   20309.179740 -3.689564e+06  1.730858e+06  4.603984e+05   
6632 -9.431069e+04   63120.714824 -1.601954e+04  7.866238e+03 -6.410496e+04   
7842 -6.528483e+06 -619211.819801 -8.399394e+05 -8.509380e+05 -9.282400e+05   
8911 -8.986742e+04  -25088.200998 -4.943305e+04 -6.949537e+04 -2.273854e+03   
9639 -4.215402e+06  198856.938343 -3.852182e+06  2.656066e+06  1.124599e+06   

                 5             6              7              8              9  \
5626 -5.848341e+05  1.006428e+06  639904.470921  -48552.906808 -556225.344649   
6632  4.230420e+04 -8.200972e+04  -31577.314572  -14316.589128   -8283.302803   
7842 -1.516675e+06  5.014806e+05  -64367.796554   41677.384772  147582.570754   
8911  9.131304e+03 -1.294742e+04   46840.449239   91263.965435  -18026.315339   
9639  6.771273e+05  8.704258e+05 -213022.620661  114223.329560  -17514.643174   

                 10             11             12             13  \
5626  409257.881363  904704.048670 -135106.488980  269526.977262   
6632   13965.410386   87155.472007  -31048.527510   15047.504536   
7842 -558286.342044  894383.453844 -461698.772420  171881.295820   
8911    8592.812821  130504.221849   -5945.331947  -49039.811000   
9639  235452.590690  724055.434398    8067.247935  268062.681285   

                 14        no  label    id  
5626 -216617.347064  35_02_-1      0  1844  
6632  -24998.574438  35_02_-1      0  1857  
7842  177717.505480  35_02_-1      0  1842  
8911  -23667.231242  35_02_-1      0  1867  
9639 -208991.111451  35_02_-1      0  1845

In [197]:
all_val[(all_val['no'] == '378_42_-1') & (all_val['label'] == predict['label'])].head()

0             1             2             3             4  \
5624  16970.744970   9581.888625  14429.690558   9222.121995  16632.002024   
5661  -3909.274166  10151.027003   8700.733947  10333.028552   5206.771227   
6269 -24368.771080   1387.949885 -23204.166784   4936.009932  -5035.951086   
6327 -38790.736097  11765.183919 -26547.637835   3315.136582 -23031.666827   
6336 -13365.474748  12849.818376 -10682.363989  -3431.526895   3390.556326   

                 5             6            7             8             9  \
5624 -13372.156089 -10132.087118  3430.582631  -2572.921555     30.131705   
5661 -10578.956124 -16160.916359  5499.574687  -7522.809155   2698.984306   
6269  18297.303101 -20630.527495 -6082.240574  29438.135677 -30656.538468   
6327   8111.950075 -29753.320167  7031.692388  38467.146148 -34494.612851   
6336  12282.212836 -22725.801366  6448.354979  32510.820442 -20229.990962   

                10            11            12            13           14  \
5624  -4750.626614 -33359.374402   8000.263443  -1035.441781  9822.350976   
5661  -3307.464866 -56825.866353  -4111.704632   1405.153603  9733.875869   
6269 -11694.343701 -54724.449016  -6217.872108  10300.532247  -810.987204   
6327  -7251.159960 -45412.097601 -10490.190182  14398.368244 -4113.161922   
6336  -5207.969662 -52091.339936  -8640.698816   -626.005742 -4557.870897   

             no  label     id  
5624  378_42_-1      0  17133  
5661  378_42_-1      0  17126  
6269  378_42_-1      0  17100  
6327  378_42_-1      0  17098  
6336  378_42_-1      0  17084

In [196]:
# IN2 同一no P N比较
m1 = get_matrix(17134) # P
m2 =  get_matrix(17133) # N
m = pairwise_distances(m1, m2)
print(m.shape)
a, b = metrics.dtw_path_from_metric(m, metric='precomputed')
b

(13, 13)


61930.300178060395

In [200]:
# IN2 不同no  P P比较
m1 = get_matrix(17134) # P
m2 =  get_matrix(1849) # P
m = pairwise_distances(m1, m2)
print(m.shape)
a, b = metrics.dtw_path_from_metric(m, metric='precomputed')
b

(13, 13)


3187792.053787003

In [201]:
# IN2 不同no  P N比较
m1 = get_matrix(17134) # P
m2 =  get_matrix(1844) # P
m = pairwise_distances(m1, m2)
print(m.shape)
a, b = metrics.dtw_path_from_metric(m, metric='precomputed')
b

(13, 13)


23348066.17273836

In [ ]:
# IN2 不同no  N N比较
m1 = get_matrix(17134) # P
m2 =  get_matrix(1844) # P
m = pairwise_distances(m1, m2)
print(m.shape)
a, b = metrics.dtw_path_from_metric(m, metric='precomputed')
b