In [1]:
import pandas as pd
import numpy as np
from tslearn.metrics import dtw
from tslearn import metrics
import time

/public/home/weixun/.conda/envs/rl/lib/python3.8/site-packages/tslearn/bases/bases.py:15: UserWarning: h5py not installed, hdf5 features will not be supported.
Install h5py to use hdf5 features: http://docs.h5py.org/
  warn(h5py_msg)


In [2]:
a = np.random.normal(3, 2.5, size=(2, 100))

In [3]:
dtw(a[0], a[1])

18.412109003436033

In [4]:
a

array([[ 4.57027896, -0.88397755,  4.35841881,  0.55092091,  3.16859498,
         5.67923209, -0.17918028,  3.7998363 ,  2.12050863,  2.85405524,
         2.40063053,  1.78571246,  4.75198929,  4.4906467 ,  0.8579952 ,
         2.23735533,  6.74371151,  1.43953497,  6.37854552,  3.09886086,
         6.5706947 ,  5.26598299,  0.93841977,  4.18225656,  4.02690686,
         6.54448786,  4.56617911,  4.07204229,  6.59607456,  1.23975002,
         1.85101636,  2.43078335,  4.02877498,  4.04126954, -1.07159453,
         5.34058536,  6.05427431,  0.63366177,  7.31379021,  3.4954647 ,
         5.59442304,  7.10123317, -0.59155524,  0.9216889 ,  1.13761247,
         7.77909342, -1.24380446,  5.40817166, -2.07197026,  5.60173839,
         5.70921146,  4.0120799 , -0.55742174,  2.93131439,  8.83881555,
         3.29441855, -0.01427736,  4.64194488,  6.7725206 ,  6.36648497,
         1.78074707,  5.80331168,  1.93563393,  3.89193804,  2.7037341 ,
         4.00847052,  4.70756121,  5.22068104,  3.7

In [5]:
a = [1,2,3]
b = [1,2,2,3,4]
dtw(a, b)

1.0

In [6]:
matrix = []
for i in range(3):
    p1 = a[i]
    m = []
    for j in range(5):
        p2 = b[j]
        x = np.power((p1-p2), 2)
        m.append(x)
    print(m)
    matrix.append(m)
print('---')
matrix

[0, 1, 1, 4, 9]
[1, 0, 0, 1, 4]
[4, 1, 1, 0, 1]
---


[[0, 1, 1, 4, 9], [1, 0, 0, 1, 4], [4, 1, 1, 0, 1]]

In [7]:
metrics.dtw_path(a, b)

([(0, 0), (1, 1), (1, 2), (2, 3), (2, 4)], 1.0)

In [13]:
metrics.dtw_path_from_metric(matrix)

ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required by check_pairwise_arrays.

In [10]:
from sklearn.metrics import pairwise_distances
a = np.array(a).reshape(1, -1)
b = np.array([2,3,2]).reshape(1, -1)

pairwise_distances(a, b)

array([[1.73205081]])

In [12]:
sum = 0
for i in range(3):
    sum += np.power((a[0,i] - b[0,i]), 2)
sum

3

In [14]:
rng = np.random.RandomState(0)
s1, s2 = rng.rand(5, 2), rng.rand(6, 2)

In [15]:
s1, s2

(array([[0.5488135 , 0.71518937],
        [0.60276338, 0.54488318],
        [0.4236548 , 0.64589411],
        [0.43758721, 0.891773  ],
        [0.96366276, 0.38344152]]),
 array([[0.79172504, 0.52889492],
        [0.56804456, 0.92559664],
        [0.07103606, 0.0871293 ],
        [0.0202184 , 0.83261985],
        [0.77815675, 0.87001215],
        [0.97861834, 0.79915856]]))

In [17]:
m = pairwise_distances(s1, s2)
m

array([[0.30612356, 0.2112843 , 0.7891329 , 0.54148195, 0.27670999,
        0.43793039],
       [0.18963685, 0.38229325, 0.70162138, 0.64973151, 0.36942074,
        0.45378731],
       [0.38621822, 0.31477278, 0.66072543, 0.44455307, 0.41940497,
        0.57573824],
       [0.50704448, 0.13477076, 0.8842009 , 0.42153982, 0.34126404,
        0.54890083],
       [0.2252094 , 0.67115269, 0.94052292, 1.04491552, 0.52073358,
        0.41598597]])

In [19]:
m.shape, s1.shape, s2.shape

((5, 6), (5, 2), (6, 2))

In [21]:
metrics.dtw_path_from_metric(m, metric='precomputed')

([(0, 0), (0, 1), (1, 2), (2, 3), (3, 4), (4, 5)], 2.4208323179319198)

In [22]:
dp = np.zeros((5, 6))
dp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
for i in range(5):
    for j in range(6):
        if i==0 and j==0:
            dp[i, j] = m[i, j]
            continue
        a, b, c = 10, 10, 10
        if i >=1 and j>=1:
            a = dp[i-1, j-1]
        if i>=1:
            b = dp[i-1, j]
        if j>=1:
            c = dp[i, j-1]
        dp[i, j] = m[i,j] + min(min(a, b), c)
dp

array([[0.30612356, 0.51740786, 1.30654076, 1.84802271, 2.1247327 ,
        2.56266309],
       [0.49576041, 0.68841681, 1.21902923, 1.86876075, 2.21744344,
        2.57852001],
       [0.88197863, 0.81053319, 1.34914224, 1.6635823 , 2.08298727,
        2.65872551],
       [1.3890231 , 0.94530396, 1.69473409, 1.77068207, 2.00484634,
        2.55374717],
       [1.6142325 , 1.61645665, 1.88582688, 2.73964961, 2.29141564,
        2.42083232]])

In [41]:
plt_data = pd.read_csv('plt_data.csv')
plt_data = plt_data[plt_data.columns[1:]]
all_val = pd.read_csv('all_val.csv')
f_13 = pd.read_csv('res/final_13.csv')
f_13 = f_13[f_13.columns[1:]]
predict = pd.read_csv('predict.csv')
plt_data.shape, all_val.shape, f_13.shape, predict.shape 

((316, 5), (11244, 17), (26329, 419), (11244, 1))

In [52]:
IN = plt_data[plt_data['kind'] == 'IN']
IN

no  len_trace kind    a1  a2
3     536_02_-1         76   IN   536   2
4    1181_02_-1         89   IN  1181   2
5    1182_02_-1         89   IN  1182   2
7      45_07_-1         78   IN    45   7
8     363_07_-1         94   IN   363   7
..          ...        ...  ...   ...  ..
305  1627_52_-1         58   IN  1627  52
311   749_54_-1         50   IN   749  54
312  1141_54_-1         54   IN  1141  54
313  1142_54_-1         54   IN  1142  54
315  1186_54_-1         48   IN  1186  54

[146 rows x 5 columns]

In [55]:
num = 0
for i in IN.index:
    FN = all_val[(all_val['no'] == IN.loc[i]['no']) &
                 (all_val['label'] != predict['label'])]
    TP = all_val[(all_val['no'] == IN.loc[i]['no']) &
                 (all_val['label'] == predict['label'])]
    # print(FN.shape[0], TP.shape[0])
    if FN.shape[0] < TP.shape[0]:
        num += 1
num

116